---
upload_path: "/static/uploads"
frontmatter_file_url_template: "/uploads"
body_file_url_template: "/uploads"
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
  author:
    default_front_matter_template: author
  book:
    default_front_matter_template: book
  catalog:
    default_front_matter_template: catalog
  event:
    default_front_matter_template: event
  genre:
    default_front_matter_template: default
  product:
    default_front_matter_template: page
  review:
    default_front_matter_template: review
  series:
    default_front_matter_template: page
  staff:
    default_front_matter_template: staff
  about:
    default_front_matter_template: page
  article:
    default_front_matter_template: article
version: '0.28'
