---
upload_path: "/static/uploads"
frontmatter_file_url_template: "/uploads"
body_file_url_template: "/uploads"
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
  series:
    default_front_matter_template: page
  staff:
    default_front_matter_template: staff
  review:
    default_front_matter_template: review
  product:
    default_front_matter_template: page
  genre:
    default_front_matter_template: default
  event:
    default_front_matter_template: event
  catalog:
    default_front_matter_template: catalog
  book:
    default_front_matter_template: book
  author:
    default_front_matter_template: author
  article:
    default_front_matter_template: article
  about:
    default_front_matter_template: page
version: '0.28'
